// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:b8851bb7-7a3f-4159-a471-f94ff6d1dfe4",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_LKIGqFlru",
    "aws_user_pools_web_client_id": "42o5hpe4u0aa6d1pck8tbp9qir",
    "aws_user_files_s3_bucket": "cognitoprototype",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
